# Generated by Django 6.0.2 on 2026-02-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heartbeat_backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="heartbeatentry",
            name="sender_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
