# Generated by Django 6.0.2 on 2026-03-02 14:27

import django.db.models.deletion
import hb_backend.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heartbeat_backend", "0003_maintenancewindow_watcherstate_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="e.g., prod-db-server", max_length=255),
                ),
                (
                    "bearer_token",
                    models.CharField(
                        db_index=True,
                        default=hb_backend.models.generate_secure_token,
                        max_length=128,
                        unique=True,
                    ),
                ),
                (
                    "aes_secret",
                    models.CharField(
                        default=hb_backend.models.generate_aes_secret,
                        max_length=64,
                    ),
                ),
                (
                    "previous_bearer_token",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                (
                    "previous_aes_secret",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("overlap_expires_at", models.BigIntegerField(blank=True, null=True)),
                (
                    "created_at",
                    models.BigIntegerField(
                        default=hb_backend.models.current_epoch_int
                    ),
                ),
                (
                    "last_rotated_at",
                    models.BigIntegerField(
                        default=hb_backend.models.current_epoch_int
                    ),
                ),
                (
                    "last_used_at",
                    models.BigIntegerField(
                        default=hb_backend.models.current_epoch_int
                    ),
                ),
                ("is_revoked", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeviceFlowSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_code",
                    models.CharField(
                        default=hb_backend.models.generate_secure_token,
                        max_length=128,
                        unique=True,
                    ),
                ),
                (
                    "user_code",
                    models.CharField(
                        default=hb_backend.models.generate_user_code,
                        max_length=9,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.BigIntegerField(
                        default=hb_backend.models.current_epoch_int
                    ),
                ),
                ("expires_at", models.BigIntegerField()),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "assigned_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
