# Generated by Django 6.0.2 on 2026-03-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heartbeat_backend", "0004_clientkey_deviceflowsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="deviceflowsession",
            name="client_name",
            field=models.CharField(default="CLI Client", max_length=255),
        ),
    ]
