# Generated by Django 6.0.2 on 2026-03-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heartbeat_backend", "0005_deviceflowsession_client_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="heartbeatentry",
            name="enforce_encryption",
            field=models.BooleanField(
                default=False,
                help_text="Strict Mode: Drop unencrypted packets from this client.",
            ),
        ),
        migrations.AddField(
            model_name="heartbeatentry",
            name="is_encrypted",
            field=models.BooleanField(
                default=False,
                help_text="High-water mark: Has this client ever sent an encrypted packet?",
            ),
        ),
        migrations.AlterField(
            model_name="alerttransitionevent",
            name="new_state",
            field=models.CharField(
                choices=[
                    ("NORMAL", "Normal"),
                    ("DEGRADED", "Degraded (Unencrypted)"),
                    ("ALERT_SENT", "Alert Sent"),
                    ("ACKNOWLEDGED", "Acknowledged"),
                    ("SNOOZED", "Snoozed"),
                    ("IN_MAINTENANCE", "In Maintenance"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="alerttransitionevent",
            name="previous_state",
            field=models.CharField(
                choices=[
                    ("NORMAL", "Normal"),
                    ("DEGRADED", "Degraded (Unencrypted)"),
                    ("ALERT_SENT", "Alert Sent"),
                    ("ACKNOWLEDGED", "Acknowledged"),
                    ("SNOOZED", "Snoozed"),
                    ("IN_MAINTENANCE", "In Maintenance"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="heartbeatentry",
            name="alert_state",
            field=models.CharField(
                choices=[
                    ("NORMAL", "Normal"),
                    ("DEGRADED", "Degraded (Unencrypted)"),
                    ("ALERT_SENT", "Alert Sent"),
                    ("ACKNOWLEDGED", "Acknowledged"),
                    ("SNOOZED", "Snoozed"),
                    ("IN_MAINTENANCE", "In Maintenance"),
                ],
                default="NORMAL",
                max_length=20,
            ),
        ),
    ]
