# Generated by Django 6.0.2 on 2026-02-26 15:51

import heartbeat_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeartbeatEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hostname", models.CharField(max_length=255)),
                ("app_name", models.CharField(max_length=255)),
                ("port", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "task",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                ("interval", models.IntegerField()),
                ("alert_after", models.IntegerField()),
                (
                    "version",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "final_report",
                    models.CharField(
                        blank=True, default=None, max_length=1024, null=True
                    ),
                ),
                ("sent_timestamp", models.BigIntegerField()),
                (
                    "received_timestamp",
                    models.BigIntegerField(
                        default=heartbeat_backend.models.current_epoch_int
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("hostname", "app_name", "port", "task"),
                        name="unique_heartbeat_source",
                    )
                ],
            },
        ),
    ]
