# Generated by Django 6.0.2 on 2026-02-28 21:53

import django.db.models.deletion
import heartbeat_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heartbeat_backend", "0002_heartbeatentry_sender_ip"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceWindow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "hostname_filter",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "app_name_filter",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "port_filter",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "task_filter",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "version_filter",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WatcherState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("has_undelivered_alerts", models.BooleanField(default=False)),
                (
                    "last_updated",
                    models.BigIntegerField(
                        default=heartbeat_backend.models.current_epoch_int
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="heartbeatentry",
            options={
                "verbose_name": "Heartbeat Entry",
                "verbose_name_plural": "Heartbeat Entries",
            },
        ),
        migrations.AddField(
            model_name="heartbeatentry",
            name="alert_state",
            field=models.CharField(
                choices=[
                    ("NORMAL", "Normal"),
                    ("ALERT_SENT", "Alert Sent"),
                    ("ACKNOWLEDGED", "Acknowledged"),
                    ("SNOOZED", "Snoozed"),
                    ("IN_MAINTENANCE", "In Maintenance"),
                ],
                default="NORMAL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="heartbeatentry",
            name="flatlined_at",
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="heartbeatentry",
            name="snoozed_until",
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name="AlertTransitionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.BigIntegerField(
                        default=heartbeat_backend.models.current_epoch_int
                    ),
                ),
                (
                    "previous_state",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("ALERT_SENT", "Alert Sent"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("SNOOZED", "Snoozed"),
                            ("IN_MAINTENANCE", "In Maintenance"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "new_state",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("ALERT_SENT", "Alert Sent"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("SNOOZED", "Snoozed"),
                            ("IN_MAINTENANCE", "In Maintenance"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "heartbeat_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions",
                        to="heartbeat_backend.heartbeatentry",
                    ),
                ),
            ],
        ),
    ]
