# Generated by Django 6.0.2 on 2026-03-02 20:14

import heartbeat_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heartbeat_backend", "0006_heartbeatentry_enforce_encryption_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientkey",
            name="expires_at",
            field=models.BigIntegerField(
                default=heartbeat_backend.models.default_key_expiry
            ),
        ),
    ]
